// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	PolicyName           string   `protobuf:"bytes,3,opt,name=PolicyName,proto3" json:"PolicyName,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	MemberOf             []string `protobuf:"bytes,5,rep,name=MemberOf,proto3" json:"MemberOf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *UserInfo) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *UserInfo) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *UserInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserInfo) GetMemberOf() []string {
	if m != nil {
		return m.MemberOf
	}
	return nil
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "models.UserInfo")
	proto.RegisterType((*Response)(nil), "models.Response")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x1d, 0x33, 0x8e, 0x33, 0xd7, 0x4d, 0xb9, 0x0b, 0x09, 0x45, 0xa4, 0xcc, 0xaa, 0xab,
	0x51, 0x74, 0xe1, 0xba, 0xb8, 0x12, 0xa9, 0x4a, 0x8a, 0x0f, 0x30, 0x4d, 0x6e, 0xa5, 0xd0, 0x4c,
	0x4a, 0x6e, 0x5c, 0xf4, 0x55, 0x7c, 0x5a, 0x49, 0xe6, 0x47, 0x77, 0xe7, 0x7e, 0x1f, 0x84, 0x73,
	0x02, 0x57, 0xad, 0xb1, 0xfb, 0xae, 0x39, 0x7a, 0x17, 0x1c, 0x16, 0xd6, 0x19, 0x3a, 0x70, 0xfd,
	0x93, 0x41, 0xf9, 0xc9, 0xe4, 0x5f, 0xba, 0x9d, 0xc3, 0x1b, 0xa8, 0x56, 0x5a, 0x13, 0xf3, 0x2b,
	0x9d, 0x64, 0xb6, 0xc8, 0x96, 0x95, 0xfa, 0x03, 0xd1, 0x6e, 0x48, 0x7b, 0x0a, 0xd1, 0x9e, 0xf7,
	0x76, 0x02, 0x78, 0x0b, 0xf0, 0xe1, 0x0e, 0x7b, 0x7d, 0x7a, 0x6b, 0x2d, 0x49, 0x91, 0xf4, 0x3f,
	0x82, 0xd7, 0x50, 0x6c, 0x42, 0x1b, 0xbe, 0x59, 0xe6, 0xc9, 0x0d, 0x17, 0xce, 0xa1, 0x5c, 0x93,
	0xdd, 0x92, 0x7f, 0xdf, 0xc9, 0x8b, 0x85, 0x58, 0x56, 0x6a, 0xba, 0xeb, 0x7b, 0x28, 0x15, 0xf1,
	0xd1, 0x75, 0x4c, 0x88, 0x90, 0x3f, 0x3b, 0x43, 0xa9, 0x96, 0x50, 0x29, 0xe3, 0x0c, 0xc4, 0x9a,
	0xbf, 0x86, 0x2e, 0x31, 0x3e, 0x3c, 0x41, 0x1e, 0xd7, 0xe0, 0x1d, 0x5c, 0xae, 0x8c, 0x49, 0x71,
	0xd6, 0xf4, 0x53, 0x9b, 0x71, 0xe6, 0x7c, 0x22, 0xe3, 0xe3, 0xf5, 0xd9, 0xb6, 0x48, 0xdf, 0xf2,
	0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xd8, 0xc4, 0x9d, 0x25, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	AddUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Response, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) AddUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/models.User/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	AddUser(context.Context, *UserInfo) (*Response, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) AddUser(ctx context.Context, req *UserInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.User/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddUser(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _User_AddUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
